<?xml version="1.0" encoding="utf-8"?>
<feature xmlns:dm0="http://schemas.microsoft.com/VisualStudio/2008/DslTools/Core" dslVersion="1.0.0.0" Id="1363802d-d745-4849-82d5-69a577e202d6" featureId="1363802d-d745-4849-82d5-69a577e202d6" scope="Web" solutionId="00000000-0000-0000-0000-000000000000" title="YearClassSiteTemplate Stamp" version="" deploymentPath="$SharePoint.Project.FileNameWithoutExtension$_$SharePoint.Feature.FileNameWithoutExtension$" xmlns="http://schemas.microsoft.com/VisualStudio/2008/SharePointTools/FeatureModel">
  <projectItems>
  </projectItems>
</feature>