<?xml version="1.0" encoding="utf-8"?>
<feature xmlns:dm0="http://schemas.microsoft.com/VisualStudio/2008/DslTools/Core" dslVersion="1.0.0.0" Id="4621eb53-bd8f-411b-a1e2-8d54c050ee07" featureId="4621eb53-bd8f-411b-a1e2-8d54c050ee07" scope="Site" solutionId="00000000-0000-0000-0000-000000000000" title="YearSiteTemplate" version="" deploymentPath="$SharePoint.Project.FileNameWithoutExtension$_$SharePoint.Feature.FileNameWithoutExtension$" xmlns="http://schemas.microsoft.com/VisualStudio/2008/SharePointTools/FeatureModel">
  <projectItems>
  </projectItems>
</feature>