<?xml version="1.0" encoding="utf-8"?>
<feature xmlns:dm0="http://schemas.microsoft.com/VisualStudio/2008/DslTools/Core" dslVersion="1.0.0.0" Id="d493fb9c-0b23-447b-9ed1-ed7e39956515" featureId="d493fb9c-0b23-447b-9ed1-ed7e39956515" scope="Web" solutionId="00000000-0000-0000-0000-000000000000" title="ClassSiteTemplate Stamp" version="" deploymentPath="$SharePoint.Project.FileNameWithoutExtension$_$SharePoint.Feature.FileNameWithoutExtension$" xmlns="http://schemas.microsoft.com/VisualStudio/2008/SharePointTools/FeatureModel">
  <projectItems>
  </projectItems>
</feature>