<?xml version="1.0" encoding="utf-8"?>
<feature xmlns:dm0="http://schemas.microsoft.com/VisualStudio/2008/DslTools/Core" dslVersion="1.0.0.0" Id="b274f977-2a59-477b-b100-8d466c230e53" featureId="b274f977-2a59-477b-b100-8d466c230e53" scope="Web" solutionId="00000000-0000-0000-0000-000000000000" title="YearSiteTemplate Welcome Page" version="" deploymentPath="$SharePoint.Project.FileNameWithoutExtension$_$SharePoint.Feature.FileNameWithoutExtension$" xmlns="http://schemas.microsoft.com/VisualStudio/2008/SharePointTools/FeatureModel">
  <projectItems>
  </projectItems>
</feature>