<?xml version="1.0" encoding="utf-8"?>
<feature xmlns:dm0="http://schemas.microsoft.com/VisualStudio/2008/DslTools/Core" dslVersion="1.0.0.0" Id="2ad98ad4-5125-43ee-b6d5-9d38e17cd788" featureId="2ad98ad4-5125-43ee-b6d5-9d38e17cd788" scope="Web" solutionId="00000000-0000-0000-0000-000000000000" title="CourseSiteTemplate Stamp" version="" deploymentPath="$SharePoint.Project.FileNameWithoutExtension$_$SharePoint.Feature.FileNameWithoutExtension$" xmlns="http://schemas.microsoft.com/VisualStudio/2008/SharePointTools/FeatureModel">
  <projectItems>
  </projectItems>
</feature>