<?xml version="1.0" encoding="utf-8"?>
<feature xmlns:dm0="http://schemas.microsoft.com/VisualStudio/2008/DslTools/Core" dslVersion="1.0.0.0" Id="95c425a5-6359-4984-9e6c-69733c254908" featureId="95c425a5-6359-4984-9e6c-69733c254908" scope="Web" solutionId="00000000-0000-0000-0000-000000000000" title="YearClassSiteTemplate Welcome Page" version="" deploymentPath="$SharePoint.Project.FileNameWithoutExtension$_$SharePoint.Feature.FileNameWithoutExtension$" xmlns="http://schemas.microsoft.com/VisualStudio/2008/SharePointTools/FeatureModel">
  <projectItems>
  </projectItems>
</feature>