<?xml version="1.0" encoding="utf-8"?>
<feature xmlns:dm0="http://schemas.microsoft.com/VisualStudio/2008/DslTools/Core" dslVersion="1.0.0.0" Id="ad598d12-7e47-4800-be92-64ca5092bdba" featureId="ad598d12-7e47-4800-be92-64ca5092bdba" scope="Site" solutionId="00000000-0000-0000-0000-000000000000" title="CourseSiteTemplate" version="" deploymentPath="$SharePoint.Project.FileNameWithoutExtension$_$SharePoint.Feature.FileNameWithoutExtension$" xmlns="http://schemas.microsoft.com/VisualStudio/2008/SharePointTools/FeatureModel">
  <projectItems>
  </projectItems>
</feature>