<?xml version="1.0" encoding="utf-8"?>
<feature xmlns:dm0="http://schemas.microsoft.com/VisualStudio/2008/DslTools/Core" dslVersion="1.0.0.0" Id="0958b601-2abc-4d6e-8ace-40e6b43d54ac" featureId="0958b601-2abc-4d6e-8ace-40e6b43d54ac" scope="Web" solutionId="00000000-0000-0000-0000-000000000000" title="ClassSiteTemplate Welcome Page" version="" deploymentPath="$SharePoint.Project.FileNameWithoutExtension$_$SharePoint.Feature.FileNameWithoutExtension$" xmlns="http://schemas.microsoft.com/VisualStudio/2008/SharePointTools/FeatureModel">
  <projectItems>
  </projectItems>
</feature>