<?xml version="1.0" encoding="utf-8"?>
<feature xmlns:dm0="http://schemas.microsoft.com/VisualStudio/2008/DslTools/Core" dslVersion="1.0.0.0" Id="9ac1d746-cbd9-4c9e-967d-00b125519e6d" featureId="9ac1d746-cbd9-4c9e-967d-00b125519e6d" scope="Site" solutionId="00000000-0000-0000-0000-000000000000" title="ClassSiteTemplate" version="" deploymentPath="$SharePoint.Project.FileNameWithoutExtension$_$SharePoint.Feature.FileNameWithoutExtension$" xmlns="http://schemas.microsoft.com/VisualStudio/2008/SharePointTools/FeatureModel">
  <projectItems>
  </projectItems>
</feature>