<?xml version="1.0" encoding="utf-8"?>
<feature xmlns:dm0="http://schemas.microsoft.com/VisualStudio/2008/DslTools/Core" dslVersion="1.0.0.0" Id="c3e4795b-b875-4aaf-a606-b40a502a210d" featureId="c3e4795b-b875-4aaf-a606-b40a502a210d" scope="Web" solutionId="00000000-0000-0000-0000-000000000000" title="YearSiteTemplate Stamp" version="" deploymentPath="$SharePoint.Project.FileNameWithoutExtension$_$SharePoint.Feature.FileNameWithoutExtension$" xmlns="http://schemas.microsoft.com/VisualStudio/2008/SharePointTools/FeatureModel">
  <projectItems>
  </projectItems>
</feature>